spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev # Default profile

# Custom application properties
app:
  database:
    url: jdbc:h2:mem:testdb
  api:
    key: default-api-key
  max-connections: 5
  scheduler:
    rate: 60000  # Configurable scheduler rate in milliseconds
  processing:
    mode: standard # Mode for DataHelperService (standard, detailed, minimal)

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
app:
  database:
    url: jdbc:h2:mem:devdb
  api:
    key: dev-api-key-1234
  max-connections: 10

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
app:
  database:
    url: jdbc:h2:mem:proddb  # In a real app, this would be a real DB URL
  api:
    key: ${API_KEY_ENV:prod-default-key} # From environment variable or default
  max-connections: 50